services:
  chat:
    build: .
    volumes:
      - ../:/workspaces:cached
    command: sleep infinity
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/chat
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.0
    command: redis-server --save 60 1 --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  db-data:
